/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Progress = IDL.Record({
  'checkpoint' : IDL.Nat,
  'completed' : IDL.Bool,
});

export const idlService = IDL.Service({
  'completeCourse' : IDL.Func([], [], []),
  'getProgress' : IDL.Func([], [Progress], ['query']),
  'resetProgress' : IDL.Func([], [], []),
  'saveProgress' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Progress = IDL.Record({
    'checkpoint' : IDL.Nat,
    'completed' : IDL.Bool,
  });
  
  return IDL.Service({
    'completeCourse' : IDL.Func([], [], []),
    'getProgress' : IDL.Func([], [Progress], ['query']),
    'resetProgress' : IDL.Func([], [], []),
    'saveProgress' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };